---

- name: include | include distro-specific tasks
  include: "{{ item_distro }}"
  with_first_found:
      - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution|lower }}.yml"
      - "{{ ansible_os_family|lower }}.yml"
  loop_control:
    loop_var: item_distro
  tags:
    - docker
