---

- name: file | create acme directory
  file:
    path: /etc/acme
    state: directory
    mode: 0600

- name: file | create acme.json
  file:
    path: /etc/acme/acme.json
    state: touch
    mode: 0600

- name: template | copy toml file
  template:
    src: traefik.j2
    dest: /etc/traefik.toml

- name: docker_container | make traefik container
  docker_container:
    name: traefik
    image: traefik
    state: started
    restart_policy: unless-stopped
    pull: True
    volumes:
    - /etc/traefik.toml:/etc/traefik/traefik.toml
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/acme:/etc/traefik/acme
    published_ports:
    - 8080:8080
    - 80:80
    - 443:443
    
