---

- name: docker_container | setup docker to bridge relay
  docker_container:
    name: tor-relay
    image: dedimax/docker-tor-relay
    state: started
    pull: true
    published_ports:
    - "9001:9001"
    - "127.0.0.1:9050:9050"
    env:
      TORRC: /etc/tor/torrc.middle
      NICKNAME: Dangernoodle
      CONTACTINFO: "Phillip <phillip@dangernoodle.de>"
    volumes:
    - /etc/localtime:/etc/localtime
    - /data/torrelay:/home/tord/.tor
