---

- name: file | make sure torrelay directory exists
  file:
    path: /data/torrelay
    state: directory

- name: template | copy tor config to server
  template:
    src: torrc.j2
    dest: /data/torrelay/torrc

- name: docker_container | setup docker to bridge relay
  docker_container:
    name: tor-relay
    image: chriswayg/tor-server
    state: started
    restart_policy: unless-stopped
    pull: true
    published_ports:
    restart: "always"
    - "9001:9001"
    - "9030:9030"
    - "/data/torrelay/torrc:/etc/tor/torrc"
